package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.ControlMehtedRelation;

public interface ControlMehtedRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_mehted_relation
     *
     * @mbggenerated
     */
    int insert(ControlMehtedRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_mehted_relation
     *
     * @mbggenerated
     */
    int insertSelective(ControlMehtedRelation record);
}