package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.ControlFileRelation;

public interface ControlFileRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_file_relation
     *
     * @mbggenerated
     */
    int insert(ControlFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_file_relation
     *
     * @mbggenerated
     */
    int insertSelective(ControlFileRelation record);
}