package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.ControlMenuRelation;

public interface ControlMenuRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_menu_relation
     *
     * @mbggenerated
     */
    int insert(ControlMenuRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_menu_relation
     *
     * @mbggenerated
     */
    int insertSelective(ControlMenuRelation record);
}