package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.ControlPageRelation;

public interface ControlPageRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_page_relation
     *
     * @mbggenerated
     */
    int insert(ControlPageRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table control_page_relation
     *
     * @mbggenerated
     */
    int insertSelective(ControlPageRelation record);
}