package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.File;

public interface FileMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated
     */
    int insert(File record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated
     */
    int insertSelective(File record);
}