package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.Methed;

public interface MethedMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methed
     *
     * @mbggenerated
     */
    int insert(Methed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table methed
     *
     * @mbggenerated
     */
    int insertSelective(Methed record);
}