package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.Page;

public interface PageMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int insert(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int insertSelective(Page record);
}