package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.RoleControlRelation;

public interface RoleControlRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_control_relation
     *
     * @mbggenerated
     */
    int insert(RoleControlRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_control_relation
     *
     * @mbggenerated
     */
    int insertSelective(RoleControlRelation record);
}