package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.SysControlRelation;

public interface SysControlRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_control_relation
     *
     * @mbggenerated
     */
    int insert(SysControlRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_control_relation
     *
     * @mbggenerated
     */
    int insertSelective(SysControlRelation record);
}