package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.SysControl;

public interface SysControlMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_control
     *
     * @mbggenerated
     */
    int insert(SysControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_control
     *
     * @mbggenerated
     */
    int insertSelective(SysControl record);
}