package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.SysInfo;

public interface SysInfoMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated
     */
    int insert(SysInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_info
     *
     * @mbggenerated
     */
    int insertSelective(SysInfo record);
}