package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.SysRoleRelation;

public interface SysRoleRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_relation
     *
     * @mbggenerated
     */
    int insert(SysRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_relation
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleRelation record);
}