package com.mijiaokj.sys.dal.repository.mapper;

import com.mijiaokj.sys.domain.UserSysRelation;

public interface UserSysRelationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_relation
     *
     * @mbggenerated
     */
    int insert(UserSysRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_sys_relation
     *
     * @mbggenerated
     */
    int insertSelective(UserSysRelation record);
}