package com.mijiaokj.sys.domain;

public class ControlPageRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_page_relation.page_id
     *
     * @mbggenerated
     */
    private Long pageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_page_relation.control_id
     *
     * @mbggenerated
     */
    private Long controlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_page_relation.page_id
     *
     * @return the value of control_page_relation.page_id
     *
     * @mbggenerated
     */
    public Long getPageId() {
        return pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_page_relation.page_id
     *
     * @param pageId the value for control_page_relation.page_id
     *
     * @mbggenerated
     */
    public void setPageId(Long pageId) {
        this.pageId = pageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_page_relation.control_id
     *
     * @return the value of control_page_relation.control_id
     *
     * @mbggenerated
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_page_relation.control_id
     *
     * @param controlId the value for control_page_relation.control_id
     *
     * @mbggenerated
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
    }
}