package com.mijiaokj.sys.domain;

public class ControlMehtedRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mehted_relation.control_id
     *
     * @mbggenerated
     */
    private Long controlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mehted_relation.methed_id
     *
     * @mbggenerated
     */
    private Long methedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mehted_relation.control_id
     *
     * @return the value of control_mehted_relation.control_id
     *
     * @mbggenerated
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mehted_relation.control_id
     *
     * @param controlId the value for control_mehted_relation.control_id
     *
     * @mbggenerated
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mehted_relation.methed_id
     *
     * @return the value of control_mehted_relation.methed_id
     *
     * @mbggenerated
     */
    public Long getMethedId() {
        return methedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mehted_relation.methed_id
     *
     * @param methedId the value for control_mehted_relation.methed_id
     *
     * @mbggenerated
     */
    public void setMethedId(Long methedId) {
        this.methedId = methedId;
    }
}