package com.mijiaokj.sys.domain;

public class ControlMenuRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_menu_relation.menu_id
     *
     * @mbggenerated
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_menu_relation.control_id
     *
     * @mbggenerated
     */
    private Long controlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_menu_relation.menu_id
     *
     * @return the value of control_menu_relation.menu_id
     *
     * @mbggenerated
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_menu_relation.menu_id
     *
     * @param menuId the value for control_menu_relation.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_menu_relation.control_id
     *
     * @return the value of control_menu_relation.control_id
     *
     * @mbggenerated
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_menu_relation.control_id
     *
     * @param controlId the value for control_menu_relation.control_id
     *
     * @mbggenerated
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
    }
}