package com.mijiaokj.sys.domain;

/**
 * 
 * @ClassName: MenuControlRelation
 * @Description: TODO 菜单操作关系
 * @author sunchenguang
 * @eamil scg16@126.com
 * @date 2016年10月14日
 *
 */
public class MenuControlRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_control_relation.menu_id
     * 菜单主键
     * @mbggenerated
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_control_relation.control_id
     * 操作主键
     * @mbggenerated
     */
    private Long controlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_control_relation.menu_id
     *
     * @return the value of menu_control_relation.menu_id
     *
     * @mbggenerated
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_control_relation.menu_id
     *
     * @param menuId the value for menu_control_relation.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_control_relation.control_id
     *
     * @return the value of menu_control_relation.control_id
     *
     * @mbggenerated
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mehted_relation.methed_id
     *
     * @param controlId the value for menu_control_relation.control_id
     *
     * @mbggenerated
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
    }
}