package com.mijiaokj.sys.domain;

/**
 * 
 * @ClassName: MenuMehtedRelation
 * @Description: TODO 菜单操作关系
 * @author sunchenguang
 * @eamil scg16@126.com
 * @date 2016年10月14日
 *
 */
public class MenuMehtedRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mehted_relation.control_id
     * 菜单主键
     * @mbggenerated
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_mehted_relation.methed_id
     * 操作主键
     * @mbggenerated
     */
    private Long methedId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mehted_relation.control_id
     *
     * @return the value of control_mehted_relation.control_id
     *
     * @mbggenerated
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mehted_relation.control_id
     *
     * @param controlId the value for control_mehted_relation.control_id
     *
     * @mbggenerated
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_mehted_relation.methed_id
     *
     * @return the value of control_mehted_relation.methed_id
     *
     * @mbggenerated
     */
    public Long getMethedId() {
        return methedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_mehted_relation.methed_id
     *
     * @param methedId the value for control_mehted_relation.methed_id
     *
     * @mbggenerated
     */
    public void setMethedId(Long methedId) {
        this.methedId = methedId;
    }
}