package com.mijiaokj.sys.domain;

public class Methed extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methed.methed_code
     *
     * @mbggenerated
     */
    private String methedCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methed.methed_name
     *
     * @mbggenerated
     */
    private String methedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column methed.methed_url
     *
     * @mbggenerated
     */
    private String methedUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methed.methed_code
     *
     * @return the value of methed.methed_code
     *
     * @mbggenerated
     */
    public String getMethedCode() {
        return methedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methed.methed_code
     *
     * @param methedCode the value for methed.methed_code
     *
     * @mbggenerated
     */
    public void setMethedCode(String methedCode) {
        this.methedCode = methedCode == null ? null : methedCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methed.methed_name
     *
     * @return the value of methed.methed_name
     *
     * @mbggenerated
     */
    public String getMethedName() {
        return methedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methed.methed_name
     *
     * @param methedName the value for methed.methed_name
     *
     * @mbggenerated
     */
    public void setMethedName(String methedName) {
        this.methedName = methedName == null ? null : methedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column methed.methed_url
     *
     * @return the value of methed.methed_url
     *
     * @mbggenerated
     */
    public String getMethedUrl() {
        return methedUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column methed.methed_url
     *
     * @param methedUrl the value for methed.methed_url
     *
     * @mbggenerated
     */
    public void setMethedUrl(String methedUrl) {
        this.methedUrl = methedUrl == null ? null : methedUrl.trim();
    }
}