package com.mijiaokj.sys.domain;

public class Page extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.page_code
     *
     * @mbggenerated
     */
    private String pageCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.page_name
     *
     * @mbggenerated
     */
    private String pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page.page_order
     *
     * @mbggenerated
     */
    private Integer pageOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.page_code
     *
     * @return the value of page.page_code
     *
     * @mbggenerated
     */
    public String getPageCode() {
        return pageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.page_code
     *
     * @param pageCode the value for page.page_code
     *
     * @mbggenerated
     */
    public void setPageCode(String pageCode) {
        this.pageCode = pageCode == null ? null : pageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.page_name
     *
     * @return the value of page.page_name
     *
     * @mbggenerated
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.page_name
     *
     * @param pageName the value for page.page_name
     *
     * @mbggenerated
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page.page_order
     *
     * @return the value of page.page_order
     *
     * @mbggenerated
     */
    public Integer getPageOrder() {
        return pageOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page.page_order
     *
     * @param pageOrder the value for page.page_order
     *
     * @mbggenerated
     */
    public void setPageOrder(Integer pageOrder) {
        this.pageOrder = pageOrder;
    }
}