package com.mijiaokj.sys.domain;

/**
 * 
 * @ClassName: RoleResRelation
 * @Description: TODO 角色资源关系表
 * @author sunchenguang
 * @eamil scg16@126.com
 * @date 2016年10月14日
 *
 */
public class RoleResRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_menu_relation.menu_id
     * 资源菜单id
     * @mbggenerated
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column control_menu_relation.control_id
     * 角色id
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_menu_relation.menu_id
     *
     * @return the value of control_menu_relation.menu_id
     *
     * @mbggenerated
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_menu_relation.menu_id
     *
     * @param menuId the value for control_menu_relation.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column control_menu_relation.control_id
     *
     * @return the value of control_menu_relation.control_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column control_menu_relation.control_id
     *
     * @param roleId the value for control_menu_relation.control_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}