package com.mijiaokj.sys.domain;

/**
 * 
 * @ClassName: RoleControl
 * @Description: TODO 角色权限表
 * @author sunchenguang
 * @eamil scg16@126.com
 * @date 2016年10月14日
 *
 */
public class RoleControl extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_control_relation.role_id
     * 角色主键
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_control_relation.control_id
     * 角色对应的操作地址
     * @mbggenerated
     */
    private String controlUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_control_relation.role_id
     *
     * @return the value of role_control_relation.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_control_relation.role_id
     *
     * @param roleId the value for role_control_relation.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_control_relation.control_id
     *
     * @return the value of role_control_relation.control_id
     *
     * @mbggenerated
     */
    public String getControlUrl() {
        return controlUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_control_relation.control_id
     *
     * @param controlId the value for role_control_relation.control_id
     *
     * @mbggenerated
     */
    public void setControlUrl(String controlUrl) {
        this.controlUrl = controlUrl;
    }
}