package com.mijiaokj.sys.domain;

public class RoleControlRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_control_relation.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_control_relation.control_id
     *
     * @mbggenerated
     */
    private Long controlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_control_relation.role_id
     *
     * @return the value of role_control_relation.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_control_relation.role_id
     *
     * @param roleId the value for role_control_relation.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_control_relation.control_id
     *
     * @return the value of role_control_relation.control_id
     *
     * @mbggenerated
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_control_relation.control_id
     *
     * @param controlId the value for role_control_relation.control_id
     *
     * @mbggenerated
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
    }
}