package com.mijiaokj.sys.domain;

public class SysControl extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_control.control_name
     *
     * @mbggenerated
     */
    private String controlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_control.control_type
     *
     * @mbggenerated
     */
    private String controlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_control.control_abstract
     *
     * @mbggenerated
     */
    private String controlAbstract;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_control.control_name
     *
     * @return the value of sys_control.control_name
     *
     * @mbggenerated
     */
    public String getControlName() {
        return controlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_control.control_name
     *
     * @param controlName the value for sys_control.control_name
     *
     * @mbggenerated
     */
    public void setControlName(String controlName) {
        this.controlName = controlName == null ? null : controlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_control.control_type
     *
     * @return the value of sys_control.control_type
     *
     * @mbggenerated
     */
    public String getControlType() {
        return controlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_control.control_type
     *
     * @param controlType the value for sys_control.control_type
     *
     * @mbggenerated
     */
    public void setControlType(String controlType) {
        this.controlType = controlType == null ? null : controlType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_control.control_abstract
     *
     * @return the value of sys_control.control_abstract
     *
     * @mbggenerated
     */
    public String getControlAbstract() {
        return controlAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_control.control_abstract
     *
     * @param controlAbstract the value for sys_control.control_abstract
     *
     * @mbggenerated
     */
    public void setControlAbstract(String controlAbstract) {
        this.controlAbstract = controlAbstract == null ? null : controlAbstract.trim();
    }
}