package com.mijiaokj.sys.domain;

public class SysControlRelation extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_control_relation.sys_id
     *
     * @mbggenerated
     */
    private Long sysId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_control_relation.control_id
     *
     * @mbggenerated
     */
    private Long controlId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_control_relation.sys_id
     *
     * @return the value of sys_control_relation.sys_id
     *
     * @mbggenerated
     */
    public Long getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_control_relation.sys_id
     *
     * @param sysId the value for sys_control_relation.sys_id
     *
     * @mbggenerated
     */
    public void setSysId(Long sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_control_relation.control_id
     *
     * @return the value of sys_control_relation.control_id
     *
     * @mbggenerated
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_control_relation.control_id
     *
     * @param controlId the value for sys_control_relation.control_id
     *
     * @mbggenerated
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
    }
}