package com.mijiaokj.sys.domain;
/**
 * 
 * @ClassName: SysInfo
 * @Description: TODO 系统信息表
 * @author sunchenguang
 * @eamil scg16@126.com
 * @date 2016年10月14日
 *
 */
public class SysInfo extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.cn_name
     *
     * @mbggenerated
     */
    private String cnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.en_name
     *
     * @mbggenerated
     */
    private String enName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.secret_key
     *
     * @mbggenerated
     */
    private String secretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_info.sys_status
     *
     * @mbggenerated
     */
    private Boolean sysStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.cn_name
     *
     * @return the value of sys_info.cn_name
     *
     * @mbggenerated
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.cn_name
     *
     * @param cnName the value for sys_info.cn_name
     *
     * @mbggenerated
     */
    public void setCnName(String cnName) {
        this.cnName = cnName == null ? null : cnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.en_name
     *
     * @return the value of sys_info.en_name
     *
     * @mbggenerated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.en_name
     *
     * @param enName the value for sys_info.en_name
     *
     * @mbggenerated
     */
    public void setEnName(String enName) {
        this.enName = enName == null ? null : enName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.secret_key
     *
     * @return the value of sys_info.secret_key
     *
     * @mbggenerated
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.secret_key
     *
     * @param secretKey the value for sys_info.secret_key
     *
     * @mbggenerated
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey == null ? null : secretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_info.sys_status
     *
     * @return the value of sys_info.sys_status
     *
     * @mbggenerated
     */
    public Boolean getSysStatus() {
        return sysStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_info.sys_status
     *
     * @param sysStatus the value for sys_info.sys_status
     *
     * @mbggenerated
     */
    public void setSysStatus(Boolean sysStatus) {
        this.sysStatus = sysStatus;
    }
}