package com.mijiaokj.sys.domain;

public class SysRole extends ReferenceObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_abstract
     *
     * @mbggenerated
     */
    private String roleAbstract;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_abstract
     *
     * @return the value of sys_role.role_abstract
     *
     * @mbggenerated
     */
    public String getRoleAbstract() {
        return roleAbstract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_abstract
     *
     * @param roleAbstract the value for sys_role.role_abstract
     *
     * @mbggenerated
     */
    public void setRoleAbstract(String roleAbstract) {
        this.roleAbstract = roleAbstract == null ? null : roleAbstract.trim();
    }
}